// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatatablesController from "./datatables_controller.js"
application.register("datatables", DatatablesController)

// import SelectController from "./select_controller.js"
// application.register("select", SelectController)

import PolymorphicSelectController from "@swobspace/stimulus-polymorphic-select"
application.register("polymorphic-select", PolymorphicSelectController)


